[package]
name = "horace"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = "1.0.203"
serde_derive = "1.0.203"
serde_json = "1.0.117"
uuid = { version = "1.8.0", features = ["serde", "v4"] }
chrono = { version = "0.4", features = ["serde"] }
