[package]
name = "finance-lib"
version = "0.1.0"
edition = "2021"

[dependencies]
uuid = { version = "1.8.0", features = ["serde", "v4"] }
iso_currency = "0.4.4"

lifesuite_common = { path = "../common" }
